import type { Competition, CompetitionWinner } from '../../types';

export const COMPETITION_SEED: Competition[] = [
  {
    id: 'climate-innovation-challenge',
    title: 'Climate Innovation Challenge',
    host: 'GreenCapital Ventures',
    prize: '$50,000 + 6-month mentorship',
    deadline: 'March 15, 2026',
    sector: 'CleanTech',
    stage: 'Idea/MVP',
    applicants: 234,
    criteria: ['Innovation (30%)', 'Feasibility (25%)', 'Impact (25%)', 'Scalability (20%)'],
    color: 'from-[#4ade80] to-[#22c55e]',
    sdg: true,
    status: 'active',
  },
  {
    id: 'web3-founders-sprint',
    title: 'Web3 Founders Sprint',
    host: 'Apex Web3 Fund',
    prize: '$30,000 + Pilot Partnership',
    deadline: 'March 8, 2026',
    sector: 'Web3',
    stage: 'Idea/MVP',
    applicants: 178,
    criteria: ['Technical Innovation (35%)', 'Market Potential (30%)', 'Team (20%)', 'Traction (15%)'],
    color: 'from-[#60a5fa] to-[#a78bfa]',
    sdg: false,
    status: 'active',
  },
  {
    id: 'saas-product-showdown',
    title: 'SaaS Product Showdown',
    host: 'Horizon VC',
    prize: '$25,000 + Investor Visibility',
    deadline: 'March 22, 2026',
    sector: 'SaaS',
    stage: 'MVP/Revenue',
    applicants: 312,
    criteria: ['Product Quality (30%)', 'Revenue Growth (30%)', 'Market Size (20%)', 'Team (20%)'],
    color: 'from-[#8b5cf6] to-[#7c3aed]',
    sdg: false,
    status: 'active',
  },
  {
    id: 'impact-startup-challenge',
    title: 'Impact Startup Challenge',
    host: 'UN SDG Capital',
    prize: '$40,000 + 0% Success Fee',
    deadline: 'April 1, 2026',
    sector: 'Any (SDG-aligned)',
    stage: 'All Stages',
    applicants: 156,
    criteria: ['SDG Impact (40%)', 'Innovation (25%)', 'Scalability (20%)', 'Team (15%)'],
    color: 'from-[#34d399] to-[#059669]',
    sdg: true,
    status: 'active',
  },
  {
    id: 'fintech-revolution-cup',
    title: 'FinTech Revolution Cup',
    host: 'BankTech Fund',
    prize: '$35K + Pilot',
    opensOn: 'Opens April 15, 2026',
    sector: 'FinTech',
    stage: 'All Stages',
    applicants: 0,
    criteria: [],
    color: 'from-[#a78bfa] to-[#f59e0b]',
    sdg: false,
    status: 'upcoming',
  },
  {
    id: 'healthtech-innovation-award',
    title: 'HealthTech Innovation Award',
    host: 'MedVentures',
    prize: '$45K + Hospital Partnership',
    opensOn: 'Opens May 1, 2026',
    sector: 'HealthTech',
    stage: 'All Stages',
    applicants: 0,
    criteria: [],
    color: 'from-[#f472b6] to-[#ec4899]',
    sdg: false,
    status: 'upcoming',
  },
  {
    id: 'student-founders-challenge',
    title: 'Student Founders Challenge',
    host: 'University Alliance Fund',
    prize: '$20K + Incubation',
    opensOn: 'Opens April 20, 2026',
    sector: 'All Sectors',
    stage: 'All Stages',
    applicants: 0,
    criteria: [],
    color: 'from-[#a78bfa] to-[#7c3aed]',
    sdg: false,
    status: 'upcoming',
  },
];

export const COMPETITION_WINNER_SEED: CompetitionWinner[] = [
  {
    id: 'winner-agrisense-2025',
    competition: 'AgriTech Africa Cup 2025',
    winner: 'AgriSense',
    prize: '$40K',
    raised: '$8.2M since',
    sector: 'AgriTech',
    place: 1,
  },
  {
    id: 'winner-neuralpay-2025',
    competition: 'DeepTech Summit 2025',
    winner: 'NeuralPay',
    prize: '$30K',
    raised: '$5.4M since',
    sector: 'FinTech',
    place: 2,
  },
  {
    id: 'winner-solarai-2024',
    competition: 'SDG Founders Pitch 2024',
    winner: 'SolarAI',
    prize: '$25K',
    raised: '$2.1M since',
    sector: 'CleanTech',
    place: 3,
  },
  {
    id: 'winner-chainvault-2024',
    competition: 'Web3 Build Sprint 2024',
    winner: 'ChainVault',
    prize: '$20K',
    raised: '$1.5M since',
    sector: 'Web3',
    place: 4,
  },
  {
    id: 'winner-codestream-2024',
    competition: 'SaaS Growth Challenge 2024',
    winner: 'CodeStream',
    prize: '$35K',
    raised: '$3.6M since',
    sector: 'SaaS',
    place: 5,
  },
];
