import type { LeaderboardEntry } from '../../types';

export const LEADERBOARD_ENTRY_SEED: LeaderboardEntry[] = [
  { id: 'overall-1', category: 'overall', rank: 1, name: 'SolarAI', sector: 'CleanTech', stage: 'MVP', score: 94, sdg: true, change: 2, desc: 'AI-driven solar energy optimization for emerging markets', investors: 47 },
  { id: 'overall-2', category: 'overall', rank: 2, name: 'NeuralPay', sector: 'FinTech', stage: 'Revenue', score: 91, sdg: false, change: 0, desc: 'Neural network fraud detection for mobile payments', investors: 38 },
  { id: 'overall-3', category: 'overall', rank: 3, name: 'AgriSense', sector: 'AgriTech', stage: 'Scaling', score: 89, sdg: true, change: 1, desc: 'IoT sensors and AI analytics for precision farming', investors: 62 },
  { id: 'overall-4', category: 'overall', rank: 4, name: 'HealthChain', sector: 'HealthTech', stage: 'MVP', score: 87, sdg: true, change: 3, desc: 'Blockchain patient records and telemedicine', investors: 29 },
  { id: 'overall-5', category: 'overall', rank: 5, name: 'CodeStream', sector: 'SaaS', stage: 'Revenue', score: 85, sdg: false, change: -1, desc: 'Developer collaboration with AI code review', investors: 55 },
  { id: 'overall-6', category: 'overall', rank: 6, name: 'WaterNet', sector: 'CleanTech', stage: 'MVP', score: 83, sdg: true, change: 5, desc: 'Smart water distribution networks', investors: 21 },
  { id: 'overall-7', category: 'overall', rank: 7, name: 'EduBlock', sector: 'EdTech', stage: 'Idea', score: 80, sdg: true, change: 4, desc: 'Decentralized credential verification', investors: 14 },
  { id: 'overall-8', category: 'overall', rank: 8, name: 'QuantumLend', sector: 'FinTech', stage: 'Revenue', score: 79, sdg: false, change: -2, desc: 'Alternative credit scoring with ML', investors: 43 },
  { id: 'overall-9', category: 'overall', rank: 9, name: 'GreenFreight', sector: 'DeepTech', stage: 'MVP', score: 77, sdg: true, change: 1, desc: 'Electric freight routing optimization', investors: 18 },
  { id: 'overall-10', category: 'overall', rank: 10, name: 'MediAlert', sector: 'HealthTech', stage: 'Idea', score: 75, sdg: false, change: 6, desc: 'AI early disease detection via wearables', investors: 12 },

  { id: 'cleantech-1', category: 'cleantech', rank: 1, name: 'SolarAI', sector: 'CleanTech', stage: 'MVP', score: 94, sdg: true, change: 1, desc: 'AI-driven solar optimization', investors: 47 },
  { id: 'cleantech-2', category: 'cleantech', rank: 2, name: 'WaterNet', sector: 'CleanTech', stage: 'MVP', score: 83, sdg: true, change: 3, desc: 'Smart water distribution', investors: 21 },
  { id: 'cleantech-3', category: 'cleantech', rank: 3, name: 'GreenFreight', sector: 'DeepTech', stage: 'MVP', score: 77, sdg: true, change: 2, desc: 'Electric freight routing', investors: 18 },
  { id: 'cleantech-4', category: 'cleantech', rank: 4, name: 'WindMapper', sector: 'CleanTech', stage: 'Idea', score: 72, sdg: true, change: 4, desc: 'Wind energy site assessment AI', investors: 9 },
  { id: 'cleantech-5', category: 'cleantech', rank: 5, name: 'CarbonTrace', sector: 'CleanTech', stage: 'Revenue', score: 70, sdg: true, change: 1, desc: 'Enterprise carbon footprint tracking', investors: 31 },
  { id: 'cleantech-6', category: 'cleantech', rank: 6, name: 'OceanClean', sector: 'CleanTech', stage: 'MVP', score: 68, sdg: true, change: 2, desc: 'Autonomous ocean plastic collection', investors: 16 },
  { id: 'cleantech-7', category: 'cleantech', rank: 7, name: 'EcoMesh', sector: 'CleanTech', stage: 'Idea', score: 65, sdg: true, change: 3, desc: 'Renewable energy microgrids for villages', investors: 7 },
  { id: 'cleantech-8', category: 'cleantech', rank: 8, name: 'AirSense', sector: 'CleanTech', stage: 'MVP', score: 63, sdg: true, change: 0, desc: 'Urban air quality monitoring network', investors: 11 },
  { id: 'cleantech-9', category: 'cleantech', rank: 9, name: 'BiogasAI', sector: 'CleanTech', stage: 'Idea', score: 60, sdg: true, change: 1, desc: 'Smart biogas plant optimization', investors: 5 },
  { id: 'cleantech-10', category: 'cleantech', rank: 10, name: 'SoilTech', sector: 'AgriTech', stage: 'MVP', score: 58, sdg: true, change: 2, desc: 'Soil health sensors for carbon farming', investors: 8 },

  { id: 'fintech-1', category: 'fintech', rank: 1, name: 'NeuralPay', sector: 'FinTech', stage: 'Revenue', score: 91, sdg: false, change: 0, desc: 'Neural network fraud detection', investors: 38 },
  { id: 'fintech-2', category: 'fintech', rank: 2, name: 'QuantumLend', sector: 'FinTech', stage: 'Revenue', score: 79, sdg: false, change: -1, desc: 'Alternative credit scoring', investors: 43 },
  { id: 'fintech-3', category: 'fintech', rank: 3, name: 'RemitSwift', sector: 'FinTech', stage: 'MVP', score: 76, sdg: true, change: 2, desc: 'Low-cost cross-border remittances', investors: 24 },
  { id: 'fintech-4', category: 'fintech', rank: 4, name: 'PensionTech', sector: 'FinTech', stage: 'Revenue', score: 74, sdg: false, change: 1, desc: 'Automated pension management', investors: 19 },
  { id: 'fintech-5', category: 'fintech', rank: 5, name: 'TrustScore', sector: 'FinTech', stage: 'Idea', score: 70, sdg: false, change: 3, desc: 'On-chain credit identity for DeFi', investors: 14 },
  { id: 'fintech-6', category: 'fintech', rank: 6, name: 'PayGrid', sector: 'FinTech', stage: 'Scaling', score: 68, sdg: false, change: -2, desc: 'Payment infrastructure for SMEs', investors: 52 },
  { id: 'fintech-7', category: 'fintech', rank: 7, name: 'MicroFund', sector: 'FinTech', stage: 'MVP', score: 65, sdg: true, change: 2, desc: 'Micro-investment platform for millennials', investors: 8 },
  { id: 'fintech-8', category: 'fintech', rank: 8, name: 'InsureAI', sector: 'FinTech', stage: 'MVP', score: 62, sdg: false, change: 0, desc: 'AI-powered microinsurance for farmers', investors: 11 },
  { id: 'fintech-9', category: 'fintech', rank: 9, name: 'CryptoKYC', sector: 'FinTech', stage: 'Revenue', score: 60, sdg: false, change: 1, desc: 'Automated KYC compliance for exchanges', investors: 27 },
  { id: 'fintech-10', category: 'fintech', rank: 10, name: 'WealthOS', sector: 'FinTech', stage: 'Idea', score: 57, sdg: false, change: 4, desc: 'Personal wealth management OS', investors: 6 },

  { id: 'web3-1', category: 'web3', rank: 1, name: 'ChainVault', sector: 'Web3', stage: 'MVP', score: 88, sdg: false, change: 3, desc: 'Decentralized asset custody protocol', investors: 34 },
  { id: 'web3-2', category: 'web3', rank: 2, name: 'NFTicket', sector: 'Web3', stage: 'Revenue', score: 82, sdg: false, change: -1, desc: 'NFT-based event ticketing platform', investors: 28 },
  { id: 'web3-3', category: 'web3', rank: 3, name: 'DAOgov', sector: 'Web3', stage: 'Idea', score: 79, sdg: false, change: 2, desc: 'DAO governance tooling for communities', investors: 17 },
  { id: 'web3-4', category: 'web3', rank: 4, name: 'GreenNFT', sector: 'Web3', stage: 'MVP', score: 76, sdg: true, change: 4, desc: 'Carbon credit NFT marketplace', investors: 21 },
  { id: 'web3-5', category: 'web3', rank: 5, name: 'MetaID', sector: 'Web3', stage: 'Idea', score: 73, sdg: false, change: 1, desc: 'Decentralized identity verification', investors: 12 },
  { id: 'web3-6', category: 'web3', rank: 6, name: 'DeFiSafe', sector: 'Web3', stage: 'Revenue', score: 71, sdg: false, change: -2, desc: 'Smart contract audit automation', investors: 39 },
  { id: 'web3-7', category: 'web3', rank: 7, name: 'Web3Pay', sector: 'Web3', stage: 'MVP', score: 68, sdg: false, change: 2, desc: 'Web3 payroll and invoicing system', investors: 15 },
  { id: 'web3-8', category: 'web3', rank: 8, name: 'LayerDAO', sector: 'Web3', stage: 'Idea', score: 65, sdg: false, change: 3, desc: 'Layer 2 governance infrastructure', investors: 9 },
  { id: 'web3-9', category: 'web3', rank: 9, name: 'TokenLaunch', sector: 'Web3', stage: 'Revenue', score: 62, sdg: false, change: 0, desc: 'Token sale compliance platform', investors: 22 },
  { id: 'web3-10', category: 'web3', rank: 10, name: 'P2PExchange', sector: 'Web3', stage: 'MVP', score: 59, sdg: false, change: 1, desc: 'Peer-to-peer crypto exchange', investors: 7 },

  { id: 'impact-1', category: 'impact', rank: 1, name: 'SolarAI', sector: 'CleanTech', stage: 'MVP', score: 94, sdg: true, change: 1, desc: 'AI-driven solar optimization for emerging markets', investors: 47 },
  { id: 'impact-2', category: 'impact', rank: 2, name: 'AgriSense', sector: 'AgriTech', stage: 'Scaling', score: 89, sdg: true, change: 2, desc: 'IoT sensors for precision farming', investors: 62 },
  { id: 'impact-3', category: 'impact', rank: 3, name: 'HealthChain', sector: 'HealthTech', stage: 'MVP', score: 87, sdg: true, change: 3, desc: 'Blockchain patient records for underserved communities', investors: 29 },
  { id: 'impact-4', category: 'impact', rank: 4, name: 'WaterNet', sector: 'CleanTech', stage: 'MVP', score: 83, sdg: true, change: 4, desc: 'Smart water distribution networks', investors: 21 },
  { id: 'impact-5', category: 'impact', rank: 5, name: 'EduBlock', sector: 'EdTech', stage: 'Idea', score: 80, sdg: true, change: 5, desc: 'Decentralized credential verification', investors: 14 },
  { id: 'impact-6', category: 'impact', rank: 6, name: 'GreenFreight', sector: 'DeepTech', stage: 'MVP', score: 77, sdg: true, change: 2, desc: 'Electric freight routing optimization', investors: 18 },
  { id: 'impact-7', category: 'impact', rank: 7, name: 'RemitSwift', sector: 'FinTech', stage: 'MVP', score: 76, sdg: true, change: 3, desc: 'Low-cost cross-border remittances', investors: 24 },
  { id: 'impact-8', category: 'impact', rank: 8, name: 'GreenNFT', sector: 'Web3', stage: 'MVP', score: 76, sdg: true, change: 1, desc: 'Carbon credit NFT marketplace', investors: 21 },
  { id: 'impact-9', category: 'impact', rank: 9, name: 'ChainCrop', sector: 'AgriTech', stage: 'MVP', score: 73, sdg: true, change: 4, desc: 'Blockchain crop insurance for smallholder farmers', investors: 11 },
  { id: 'impact-10', category: 'impact', rank: 10, name: 'MicroFund', sector: 'FinTech', stage: 'MVP', score: 65, sdg: true, change: 2, desc: 'Micro-investment for millennials', investors: 8 },

  { id: 'rising-1', category: 'rising', rank: 1, name: 'MediAlert', sector: 'HealthTech', stage: 'Idea', score: 75, sdg: false, change: 12, desc: 'AI early disease detection via wearables', investors: 12 },
  { id: 'rising-2', category: 'rising', rank: 2, name: 'EduBlock', sector: 'EdTech', stage: 'Idea', score: 80, sdg: true, change: 9, desc: 'Decentralized credential verification', investors: 14 },
  { id: 'rising-3', category: 'rising', rank: 3, name: 'WindMapper', sector: 'CleanTech', stage: 'Idea', score: 72, sdg: true, change: 8, desc: 'Wind energy site assessment AI', investors: 9 },
  { id: 'rising-4', category: 'rising', rank: 4, name: 'WaterNet', sector: 'CleanTech', stage: 'MVP', score: 83, sdg: true, change: 7, desc: 'Smart water distribution networks', investors: 21 },
  { id: 'rising-5', category: 'rising', rank: 5, name: 'DAOgov', sector: 'Web3', stage: 'Idea', score: 79, sdg: false, change: 7, desc: 'DAO governance tooling', investors: 17 },
  { id: 'rising-6', category: 'rising', rank: 6, name: 'GreenNFT', sector: 'Web3', stage: 'MVP', score: 76, sdg: true, change: 6, desc: 'Carbon credit NFT marketplace', investors: 21 },
  { id: 'rising-7', category: 'rising', rank: 7, name: 'HealthChain', sector: 'HealthTech', stage: 'MVP', score: 87, sdg: true, change: 5, desc: 'Blockchain patient records', investors: 29 },
  { id: 'rising-8', category: 'rising', rank: 8, name: 'ChainCrop', sector: 'AgriTech', stage: 'MVP', score: 73, sdg: true, change: 5, desc: 'Blockchain crop insurance', investors: 11 },
  { id: 'rising-9', category: 'rising', rank: 9, name: 'CarbonTrace', sector: 'CleanTech', stage: 'Revenue', score: 70, sdg: true, change: 4, desc: 'Enterprise carbon footprint tracking', investors: 31 },
  { id: 'rising-10', category: 'rising', rank: 10, name: 'RemitSwift', sector: 'FinTech', stage: 'MVP', score: 76, sdg: true, change: 4, desc: 'Low-cost remittances', investors: 24 },

  { id: 'investor-1', category: 'investor', rank: 1, name: 'AgriSense', sector: 'AgriTech', stage: 'Scaling', score: 89, sdg: true, change: 1, desc: 'IoT sensors for precision farming', investors: 62 },
  { id: 'investor-2', category: 'investor', rank: 2, name: 'CodeStream', sector: 'SaaS', stage: 'Revenue', score: 85, sdg: false, change: 0, desc: 'Developer collaboration platform', investors: 55 },
  { id: 'investor-3', category: 'investor', rank: 3, name: 'PayGrid', sector: 'FinTech', stage: 'Scaling', score: 68, sdg: false, change: -1, desc: 'Payment infrastructure for SMEs', investors: 52 },
  { id: 'investor-4', category: 'investor', rank: 4, name: 'SolarAI', sector: 'CleanTech', stage: 'MVP', score: 94, sdg: true, change: 2, desc: 'AI-driven solar optimization', investors: 47 },
  { id: 'investor-5', category: 'investor', rank: 5, name: 'QuantumLend', sector: 'FinTech', stage: 'Revenue', score: 79, sdg: false, change: -1, desc: 'Alternative credit scoring', investors: 43 },
  { id: 'investor-6', category: 'investor', rank: 6, name: 'NeuralPay', sector: 'FinTech', stage: 'Revenue', score: 91, sdg: false, change: 0, desc: 'Neural network fraud detection', investors: 38 },
  { id: 'investor-7', category: 'investor', rank: 7, name: 'ChainVault', sector: 'Web3', stage: 'MVP', score: 88, sdg: false, change: 2, desc: 'Decentralized asset custody', investors: 34 },
  { id: 'investor-8', category: 'investor', rank: 8, name: 'NFTicket', sector: 'Web3', stage: 'Revenue', score: 82, sdg: false, change: -2, desc: 'NFT-based event ticketing', investors: 28 },
  { id: 'investor-9', category: 'investor', rank: 9, name: 'CryptoKYC', sector: 'FinTech', stage: 'Revenue', score: 60, sdg: false, change: 1, desc: 'Automated KYC compliance', investors: 27 },
  { id: 'investor-10', category: 'investor', rank: 10, name: 'RemitSwift', sector: 'FinTech', stage: 'MVP', score: 76, sdg: true, change: 1, desc: 'Cross-border remittances', investors: 24 },
];
